### ISSUE TITLE
Running zipProd will by default include server-obf.jar

### ISSUE THREAD

**Issue by NeunEinser** [jacobsjo/MinecraftMultiNoiseVisualization#5]
When running zipProd, it will include the server-deobf.jar.

This may lead to accidentally including it in a release.

**Comment by jacobsjo** [comment]
That would indeed not be ideal.

Unfortunately, I am a bit short of time in the next 2 weeks. If anyone fixes this in a pull request, I'll merge that, otherwise this will have to wait till then.
